# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloworld.proto',
  package='helloworld',
  syntax='proto3',
  serialized_options=b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10helloworld.proto\x12\nhelloworld\"\x12\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty\":\n\nMedication\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nintakeTime\x18\x03 \x01(\x03\"/\n\x0eUserMedication\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\r\n\x05medId\x18\x02 \x01(\x05\"3\n\x0bMedications\x12$\n\x04meds\x18\x01 \x03(\x0b\x32\x16.helloworld.Medication2\xe2\x01\n\x0eMedApplication\x12=\n\x0eGetMedications\x12\x10.helloworld.User\x1a\x17.helloworld.Medications\"\x00\x12\x46\n\x13MarkMedicationTaken\x12\x1a.helloworld.UserMedication\x1a\x11.helloworld.Empty\"\x00\x12I\n\x16MarkMedicationNotTaken\x12\x1a.helloworld.UserMedication\x1a\x11.helloworld.Empty\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='helloworld.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='helloworld.User.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=50,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='helloworld.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=59,
)


_MEDICATION = _descriptor.Descriptor(
  name='Medication',
  full_name='helloworld.Medication',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='helloworld.Medication.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='helloworld.Medication.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='intakeTime', full_name='helloworld.Medication.intakeTime', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=119,
)


_USERMEDICATION = _descriptor.Descriptor(
  name='UserMedication',
  full_name='helloworld.UserMedication',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='helloworld.UserMedication.userId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='medId', full_name='helloworld.UserMedication.medId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=168,
)


_MEDICATIONS = _descriptor.Descriptor(
  name='Medications',
  full_name='helloworld.Medications',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='meds', full_name='helloworld.Medications.meds', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=221,
)

_MEDICATIONS.fields_by_name['meds'].message_type = _MEDICATION
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Medication'] = _MEDICATION
DESCRIPTOR.message_types_by_name['UserMedication'] = _USERMEDICATION
DESCRIPTOR.message_types_by_name['Medications'] = _MEDICATIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.User)
  })
_sym_db.RegisterMessage(User)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Empty)
  })
_sym_db.RegisterMessage(Empty)

Medication = _reflection.GeneratedProtocolMessageType('Medication', (_message.Message,), {
  'DESCRIPTOR' : _MEDICATION,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Medication)
  })
_sym_db.RegisterMessage(Medication)

UserMedication = _reflection.GeneratedProtocolMessageType('UserMedication', (_message.Message,), {
  'DESCRIPTOR' : _USERMEDICATION,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.UserMedication)
  })
_sym_db.RegisterMessage(UserMedication)

Medications = _reflection.GeneratedProtocolMessageType('Medications', (_message.Message,), {
  'DESCRIPTOR' : _MEDICATIONS,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Medications)
  })
_sym_db.RegisterMessage(Medications)


DESCRIPTOR._options = None

_MEDAPPLICATION = _descriptor.ServiceDescriptor(
  name='MedApplication',
  full_name='helloworld.MedApplication',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=224,
  serialized_end=450,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMedications',
    full_name='helloworld.MedApplication.GetMedications',
    index=0,
    containing_service=None,
    input_type=_USER,
    output_type=_MEDICATIONS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MarkMedicationTaken',
    full_name='helloworld.MedApplication.MarkMedicationTaken',
    index=1,
    containing_service=None,
    input_type=_USERMEDICATION,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MarkMedicationNotTaken',
    full_name='helloworld.MedApplication.MarkMedicationNotTaken',
    index=2,
    containing_service=None,
    input_type=_USERMEDICATION,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEDAPPLICATION)

DESCRIPTOR.services_by_name['MedApplication'] = _MEDAPPLICATION

# @@protoc_insertion_point(module_scope)
